### PR TITLE
USART_Task2

### PR DESCRIPTION
**Pull request by KhalidMosad**

### CODE REVIEW

**Comment by M-Wagdy** [comment]
Why is there EEPROM,SPI, and TWI in the MCAL as they aren't needed in this task (Sidenote: EEPROM should be in HAL). Also, i didn't find any flowchart or static design for the project.

**Comment by M-Wagdy** [comment]
The APP doesn't handle backspace in getting string. e.g if i write "STAP" then backspace twice to "ST" and then write the correct spelling "STOP", it doesn't turn on the red light.

**Comment by KhalidMosad** [comment]
> The APP doesn't handle backspace in getting string. e.g if i write "STAP" then backspace twice to "ST" and then write the correct spelling "STOP", it doesn't turn on the red light.

I depend on pressing Enter no Backspace..

**Comment by KhalidMosad** [comment]
> Why is there EEPROM,SPI, and TWI in the MCAL as they aren't needed in this task (Sidenote: EEPROM should be in HAL). Also, i didn't find any flowchart or static design for the project.

I always include the whole folder in my project and i just include what i will use, but it's okay i will handle that.
i will push the flowchart soon and inform you. 
Thank you, Wagdy.

**Comment by M-Wagdy** [comment]
Great i get it then no need to handle i guess?

Waiting for the flowchart, Thanks Khalid.

**Comment by KhalidMosad** [comment]
> Great i get it then no need to handle i guess?
> 
> Waiting for the flowchart, Thanks Khalid.

I added Flowchart and static design for all project, Can you please review again ?

**Pull request merged**
