### PR TITLE
EEPROM task

### PR DESCRIPTION
**Pull request by KhalidMosad**

### CODE REVIEW

**Comment by M-Wagdy** [comment]
image
Data is written to Two bytes not one

**Comment by KhalidMosad** [comment]
> image
> Data is written to Two bytes not one

Pull the changes and review
Thank you for your feedback.

**Comment by M-Wagdy** [comment]
I didn't find any flowchart or static design for the project.

**Comment by KhalidMosad** [comment]
> I didn't find any flowchart or static design for the project.

Yes you're right i will inform you once i push them 😄

**Comment by KhalidMosad** [comment]
> I didn't find any flowchart or static design for the project.

Hey, Wagdy.
I Pushed Static and dynamic dynamic design....

**Pull request merged**
